# These are supported funding model platforms

github: [blib-la]
patreon: Blib_la
open_collective: blibla
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
# Modified 2024-04-06
# Modified 2024-04-25
# Modified 2024-05-13
# Modified 2024-08-06
# Modified 2024-08-26
# Modified 2024-10-01
# Modified 2025-05-27
# Modified 2025-11-06
# Modified 2025-12-12
# Modified 2026-01-09
# Modified 2024-05-07
# Modified 2024-08-01
# Modified 2024-10-28
# Modified 2025-04-14
# Modified 2025-08-06
# Modified 2025-09-10
# Modified 2024-02-25
# Modified 2024-03-05
# Modified 2024-03-21
# Modified 2024-04-03
# Modified 2024-04-09
# Modified 2024-04-10
# Modified 2024-04-16
# Modified 2024-04-18
# Modified 2024-08-23
# Modified 2024-09-13
# Modified 2024-10-24
# Modified 2024-12-27
# Modified 2025-01-21
# Modified 2025-02-20
# Modified 2025-08-19
# Modified 2025-12-29
# Modified 2024-02-16
# Modified 2024-04-19
# Modified 2024-05-16
# Modified 2024-05-20
# Modified 2024-06-27
# Modified 2024-08-20
# Modified 2024-09-02
# Modified 2024-09-10
# Modified 2024-09-27
# Modified 2024-10-01
# Modified 2024-10-29
# Modified 2024-11-04
# Modified 2024-11-07
# Modified 2024-11-09
# Modified 2025-01-01
# Modified 2025-01-06
# Modified 2025-01-07
# Modified 2025-01-20
# Modified 2025-01-21
